### ISSUE TITLE
Sorry but where is the config file?

### ISSUE THREAD

**Issue by Senwang98** [SPengLiang/WeakM3D#1]
@SPengLiang 
hello, bro, meet you again.
I'm interesting about your work.
But it seems that you forget to upload `config` file into the repo.
Good luck & wish for your reply.

**Comment by SPengLiang** [comment]
Thank you for reminding! I have uploaded the config.

**Comment by Senwang98** [comment]
@SPengLiang 
Another thing to disturb you.
I find the download script of `KITTI raw data` is accessible in our country.
Do you have a suggestion about downloading the raw data? (Use `迅雷` to download in batches?)
(The original data has too many small data sets, and it is not realistic to download one by one.)

**Comment by SPengLiang** [comment]
> @SPengLiang Another thing to disturb you. I find the download script of `KITTI raw data` is accessible in our country. Do you have a suggestion about downloading the raw data? (Use `迅雷` to download in batches?) (The original data has too many small data sets, and it is not realistic to download one by one.)

Hi~ you can use `wget` to download in batches. I did not try `迅雷`, maybe it also works.
Feel free to contact me if you have further questions/concerns.

**Comment by Senwang98** [comment]
@SPengLiang 
So is it normal for you to download with `wget` before? 
I found that KITTI dataset did not support `wget` download in China about 3 months ago.

**Comment by SPengLiang** [comment]
That's too bad。
I used `wget` to download the data about 2-3 years ago, and recently I did not try. 
You can try other commands.
And I will also try to fix this download problem when I have free time.

**Comment by Senwang98** [comment]
@SPengLiang 
Fine, thanks bro.
